export const PLANETS = [
    /* - - Sun - - */
    {
        name: "sun",
        displayName: "Matahari",
        caption: "Sang Surya",
        description: "Matahari adalah pusat tata surya kita. Suhu inti matahari adalah sekitar 15 juta °C (27 juta °F).",
        year: "230 juta tahun bumi",
        day: null,
        radius: 695508,
        meanTemp: 5500,
        timesLarger: 109.2,
        orbitalVelocity: 0,
        orbitObject: null,
        orbitalRadius: 0,
        scaledOrbitalRadius: 0,
        rotationVelocity: 2,
        orbitalInclination: 0,
        axialTilt: 7.25,
    },
    /* - - Sun - - */

    /* - - Planets - - */
    {
        name: "mercury",
        displayName: "Merkurius",
        caption: "Bintang Senja",
        description: "Merkurius adalah planet tercepat dan terkecil di tata surya. Di permukaan, matahari akan tampak 3 kali lebih besar dari yang terlihat di Bumi",
        year: "88 hari Bumi",
        day: "59 hari Bumi",
        moons: 0,
        distanceFromSun: 0.4,
        minTemp: -170,
        maxTemp: 449,
        radius: 2439.7,
        timesLarger: 0.38,
        orbitalVelocity: 47.9, 
        orbitObject: "sun",
        orbitalRadius: 57909050, 
        scaledOrbitalRadius: 24, 
        rotationVelocity: 0.003,
        orbitalInclination: 7,
        axialTilt: 0.03,
    },
    {
        name: "venus",
        displayName: "Venus",
        caption: "Bintang Kejora",
        description: "Venus adalah planet terpanas di tata surya. Hal ini disebabkan oleh atmosfernya yang tebal menjebak panas di dalam dan menimbulkan efek rumah kaca.",
        year: "225 hari Bumi",
        day: "243 hari Bumi",
        moons: 0,
        distanceFromSun: 0.7,
        meanTemp: 465,
        radius: 6051.8,
        timesLarger: 0.9,
        orbitalVelocity: 35.0, 
        orbitObject: "sun",
        orbitalRadius: 108200000, 
        scaledOrbitalRadius: 31, 
        rotationVelocity: 0.003,
        orbitalInclination: 3.4,
        axialTilt: 177,
    },
    {
        name: "earth",
        displayName: "Bumi",
        caption: "Planet Biru",
        description: "Bumi adalah satu-satunya planet di tata surya kita yang memiliki air di permukaannya. Atmosfer memungkinkan kita sebagai manusia untuk bernapas, sekaligus melindungi kita dari meteoroid.",
        year: "365.25 hari Bumi",
        day: "23.9 jam",
        moons: 1,
        distanceFromSun: 1,
        minTemp: -89,
        maxTemp: 58,
        radius: 6371,
        timesLarger: -1,
        orbitalVelocity: 29.8,
        orbitObject: "sun",
        orbitalRadius: 149600000, 
        scaledOrbitalRadius: 37,
        rotationVelocity: 0.46,
        orbitalInclination: 0,
        axialTilt: 23.44,
    },
    {
        name: "mars",
        displayName: "Mars",
        caption: "Planet Merah",
        description: "Mars adalah kandidat terbaik untuk hidup di luar Bumi. Ini adalah satu-satunya planet yang dikirim penjelajah. Sampel Mars milik penjelajah Perseverance akan sampai ke Bumi pada tahun 2033.",
        year: "1.88 tahun Bumi",
        day: "24.6 jam",
        moons: 2,
        distanceFromSun: 1.5,
        minTemp: -125,
        maxTemp: 20,
        radius: 3389.5,
        timesLarger: 0.52,
        orbitalVelocity: 24.1, 
        orbitObject: "sun",
        orbitalRadius: 227939366, 
        scaledOrbitalRadius: 45, 
        rotationVelocity: 0.241,
        orbitalInclination: 1.8,
        axialTilt: 25.19,
    },
    {
        name: "jupiter",
        displayName: "Jupiter",
        caption: "Planet Raksasa",
        description: "Jupiter adalah planet terbesar di tata surya kita. The Great Red Spot adalah badai super Jupiter yang berukuran dua kali Bumi dan telah berlangsung selama lebih dari 100 tahun.",
        year: "11.86 tahun Bumi",
        day: "9.93 jam",
        moons: 79,
        distanceFromSun: 5.1,
        meanTemp: -110,
        radius: 69911,
        timesLarger: 11,
        orbitalVelocity: 24.1, 
        orbitObject: "sun",
        orbitalRadius: 778412027, 
        scaledOrbitalRadius: 72, 
        rotationVelocity: 12.6,
        orbitalInclination: 1.3,
        axialTilt: 3.13,
    },
    {
        name: "saturn",
        displayName: "Saturnus",
        caption: "Planet Bercincin",
        description: "Saturnus bukan satu-satunya planet bercincin di tata surya kita, namun tidak ada yang seindah Saturnus. Saturnus memiliki total 7 cincin.",
        year: "29.45 tahun Bumi",
        day: "10.7 jam",
        moons: 82,
        distanceFromSun: 9.5,
        meanTemp: -140,
        radius: 58232,
        timesLarger: 9.1,
        orbitalVelocity: 9.7, 
        orbitObject: "sun",
        orbitalRadius: 1433530000, 
        scaledOrbitalRadius: 108, 
        rotationVelocity: 9.87,
        orbitalInclination: 2.5,
        axialTilt: 26.73,
    },
    {
        name: "uranus",
        displayName: "Uranus",
        caption: "Petualang Misterius",
        description: "Planet ini memiliki arah rotasi yang berlawanan dengan Bumi. Pergerakan yang unik dan tidak bisa diperkirakan inilah yang membuatnya menjadi misterius.",
        year: "84 tahun Bumi",
        day: "17 jam",
        moons: 27,
        distanceFromSun: 19.8,
        meanTemp: -195,
        radius: 25362,
        timesLarger: 4,
        orbitalVelocity: 6.8, 
        orbitObject: "sun",
        orbitalRadius: 2870972000, 
        scaledOrbitalRadius: 145, 
        rotationVelocity: 2.59,
        orbitalInclination: 0.8,
        axialTilt: 82.23,
    },
    {
        name: "neptune",
        displayName: "Neptunus",
        caption: "Pembuat Masalah",
        description: "Planet ini memiliki daya gravitasi yang paling kuat sehingga sering menarik benda langit di sekitarnya. NASA's Voyager 2 terbang ke Neptunus tahun 1989 membuat itu menmbuat itu menjadi pesawat luar angkasa pertama yang mendekat.",
        year: "164 tahun Bumi",
        day: "16 jam",
        moons: 14,
        distanceFromSun: 30.1,
        meanTemp: -200,
        radius: 24622,
        timesLarger: 3.9,
        orbitalVelocity: 5.4, 
        orbitObject: "sun",
        orbitalRadius: 4514953000, 
        scaledOrbitalRadius: 180, 
        rotationVelocity: 2.6,
        orbitalInclination: 1.8,
        axialTilt: 28.32,
    },
    /* - - Sun - - */

    /* - - Moons - - */
    {
        name: "moon",
        displayName: "Bulan",
        caption: "Benda Paling Terang di Langit Malam",
        description: "Bulan adalah satelit terbesar kelima di tata surya kita. Bulan sejauh ini telah dikunjungi oleh 24 manusia dan lebih dari 105 pengunjung robot.",
        year: "27 hari",
        radius: 1737.5,
        timesLarger: 0.27,
        distance: 385000,
        minTemp: -173,
        maxTemp: 127,
        orbitalVelocity: 1.022,
        orbitObject: "earth",
        orbitalRadius: 385000, 
        scaledOrbitalRadius: 3,
        rotationVelocity: 0.005,
        orbitalInclination: 5.1,
    },
    {
        name: "io",
        displayName: "Io",
        caption: "Aktivitas Vulkanik Terbanyak",
        description: "Io sangat aktif secara vulkanik sehingga memiliki danau yang terbuat dari lava. Beberapa gunung berapinya sangat kuat sehingga dapat dilihat dari Bumi dengan teleskop.",
        year: "42 jam",
        radius: 1821.6,
        timesLarger: 0.285,
        distance: 262000,
        meanTemp: -143,
        orbitalVelocity: 17.334,
        orbitObject: "jupiter",
        orbitalRadius: 262000, 
        scaledOrbitalRadius: 10,
        rotationVelocity: 0.07,
        orbitalInclination: 0.05,
    },
    {
        name: "europa",
        displayName: "Europa",
        caption: "Satelit yang Menjanjikan Kehidupan",
        description: "Lautan air asin di bawah permukaan Europa mengandung air dua kali lebih banyak dibandingkan lautan di Bumi. Ada kemungkinan bahwa di bawah permukaan bekunya terdapat suatu bentuk kehidupan.",
        year: "85 jam",
        radius: 1560.8,
        timesLarger: 0.24,
        distance: 670900,
        minTemp: -220,
        maxTemp: -160,
        orbitalVelocity: 13.743,
        orbitObject: "jupiter",
        orbitalRadius: 670900, 
        scaledOrbitalRadius: 13,
        rotationVelocity: 0.03,
        orbitalInclination: 0.47,
    },
    {
        name: "ganymede",
        displayName: "Ganymeda",
        caption: "Satelit Terbesar di Tata Surya",
        description: "Ganymeda adalah satelit yang lebih besar dari Merkurius. Ganymeda memiliki lautan bawah tanah dan atmosfer oksigen yang lemah. Satelit ini juga hanya memiliki medan magnetnya sendiri.",
        year: "172 jam",
        radius: 2634.1,
        timesLarger: 0.416,
        distance: 1070400,
        minTemp: -180,
        maxTemp: -113,
        orbitalVelocity: 10.880,
        orbitObject: "jupiter",
        orbitalRadius: 1070400, 
        scaledOrbitalRadius: 15,
        rotationVelocity: 0.026,
        orbitalInclination: 0.2,
    },
    {
        name: "callisto",
        displayName: "Callisto",
        caption: "Satelit yang Sudah Lama Mati",
        description: "Callisto adalah objek dengan kawah paling banyak di tata surya kita. Hampir tidak ada aktivitas geologis di permukaannya, namun mungkin terdapat lautan di bawah permukaannya.",
        year: "17 hari",
        radius: 2410.3,
        timesLarger: 0.384,
        distance: 1883000,
        minTemp: -193,
        maxTemp: -108,
        orbitalVelocity: 8.204,
        orbitObject: "jupiter",
        orbitalRadius: 1883000, 
        scaledOrbitalRadius: 17.5,
        rotationVelocity: 0.01,
        orbitalInclination: 0.28,
    },
    {
        name: "titan",
        displayName: "Titan",
        caption: "Satelit dengan Cairan di Permukaannya",
        description: "Titan adalah satu-satunya satelit di tata surya kita yang memiliki awan dan atmosfer padat. Ada juga danau dan lautan di permukaannya, namun terbuat dari metana dan etana.",
        year: "16 hari",
        radius: 2574.7,
        timesLarger: 0.4,
        distance: 1221865,
        meanTemp: -179,
        orbitalVelocity: 5.57,
        orbitObject: "saturn",
        orbitalRadius: 1221865, 
        scaledOrbitalRadius: 16,
        rotationVelocity: 0.011,
        orbitalInclination: 0.33,
    },
    {
        name: "triton",
        displayName: "Triton",
        caption: "Benda Terdingin di Tata Surya",
        description: "Triton adalah bulan terdingin di tata surya kita. Ia juga merupakan satelit terbesar yang mengorbit berlawanan arah rotasi planetnya.",
        year: "141 jam",
        radius: 1353.4,
        timesLarger: 0.21,
        distance: 354759,
        meanTemp: -235,
        orbitalVelocity: 4.39,
        orbitObject: "neptune",
        orbitalRadius: 354759, 
        scaledOrbitalRadius: 7,
        rotationVelocity: 0.017,
        orbitalInclination: 156.885,
    },
    /* - - Moons - - */
]